services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend_image
    container_name: backend_container
    restart: always
    environment:
      - DB_HOST_NAME=postgres_container
      - DB_PORT=5432
      - DB_PASSWORD=123123
      - DB_NAME=postgres
      - DB_USER=postgres
      - SECRET_KEY=secret_key
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123123
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5431:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  postgres-db:
